---
name: admin-ui
director_uuid: 1e62421b-717e-438c-b5e8-b1b64a9bce23 # CHANGE: Director UUID
release:
  name: admin-ui
  version: latest
compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.small
update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4
  max_errors: 1
networks:
- name: default
  type: dynamic
  cloud_properties:
    security_groups:
    - default
resource_pools:
- name: common
  network: default
  size: 1
  stemcell:
    name: bosh-stemcell
    version: latest
  cloud_properties:
    instance_type: m1.small
jobs:
- name: admin_ui
  template: admin_ui
  instances: 1
  resource_pool: common
  networks:
  - name: default
    default: [ dns, gateway ]
properties:
  admin_ui:
    cloud_controller_uri: http://api.example.com # CHANGE: Api enpoint of Cloud Controller to monitor
    uaa_admin_credentials:
      username: cc_admin # CHANGE: Username of a privileged user on the target Cloud Controller
      password: passw0rd # CHANGE: Password of this user
    ui_admin_credentials:
      username: admin # CHANGE: Username of the admin_ui admin user
      password: admin # CHANGE: Password of this user
    ui_credentials:
      username: user # CHANGE: Username of the admin_ui normal user
      password: user # CHANGE: Password of this user
    uri: admin.example.com # CHANGE: Uri of the admin_ui will be registered at the gorouter
  networks: 
    apps: default
  nats: # CHANGE: Copy paste below section from the to be monitored Cloud Foundry deployment
    user: nats 
    password: nats 
    address: 0.nats.default.cf.microbosh 
    port: 4222 
